### ISSUE TITLE
Øke linjelengde til 180 tegn

### ISSUE THREAD

**Issue by raphw** [Skatteetaten/checkstyle-config#9]
Jeg vil gjerne forslå at vi øker antall tegn per linje. I praksis blir denne regelen oftest ignorert og takket 'broken window theorem' fører det ofte at man også ignorerer andre regler.

180 tegn kan vises på nesten alle skjerm og innimellom er lange linjer mer lesbar enn mange.

**Comment by stenaksel** [comment]
Som jeg har kommenter på tidligere i vår wiki også er jeg helt enig i at vi har for kort linjelengde i dag.

**Comment by olek-ske** [comment]
Trodde denne ballen var lagt død for lengst da man økte med 50% fra 80 til 120, se "[Skatteetatens kodestandard for Java & Kotlin](https://wiki.sits.no/x/DBMoAw)"

**Ennå ikke overbevist?**
Sjekk ut JavaZone-foredraget "[How to Write a Method](https://vimeo.com/74316116)" av Kevlin Henney
Spol fram til 
* 05:00 How Java programmers lay out their code
eller 
* 08:30 Code review, in a room with a projector

**Comment by raphw** [comment]
Jeg tenker at vi kan være enig om at en kortere linje med samme informasjonsinnhold er bedre enn en som er lengre.

Samtidig fastsetter checkstyle en øvre grense, ikke en anbefaling for en gjennomsnittlig kodelinje. Denne begrensningen treffer oss fort i setter/getter-intensiv kode med XSD-genererte typer hvor noen linjer må plutselig deles opp som reduserer lesbarheten. 

Java som språk har forandret seg veldig siden 2013, men lambdas får man fort mer nesting enn før, og det har blitt mer vanlig med større skjerm og bedre oppløsning. Det er sant at dette kan redusere muligheten til kodereview med prosjektor, men jeg har aldri gjort en slik review i min tid i skatt mens jeg jobber daglig med en skjerm som uten problem kunne vise lengre linjer. 

Jeg opplever at checkstyle blir ignorert i økende grad på grunn av linjebegrensning. Og siden det er lett å ignorere en varsel når det allerede finnes en fra før gjør dette checkstyle til et slags unhelpsome noise som man likegodt kan avvikle i mange prosjekt. Samtidig kunne prosjekt som jobber slik at en linjebegrensning ansees som god bruke en ekstra regel som også kunne lett tilbys i dette prosjektet.

**Comment by olek-ske** [comment]
> Jeg tenker at vi kan være enig om at en kortere linje med samme informasjonsinnhold er bedre enn en som er lengre.

Her er alle enig. Men å skrive kort og konsist er vanskelig...

> Jeg opplever at checkstyle blir ignorert i økende grad på grunn av linjebegrensning.

Denne skjønte jeg ikke. ChekStyle er jo obligatorisk i Jenkins/aurora-pipeline-scripts

**Comment by raphw** [comment]
Nei, det er ikke det. Og selv om du bruker checkstyle trenger du ikke å feile bygget.

For vår XSD og lambda tung kode viser reglene seg som upraktisk, vi velger derfor å ikke feile byggene.

**Comment by olek-ske** [comment]
@raphw, @Aerlant har lagt inn checkstyle-with-metrics-extra-linelength.xml. Kan denne saken lukkes?

**Comment by Aerlant** [comment]
Ansees som løst :)
